### ISSUE TITLE
Images for README

### ISSUE THREAD

**Issue by SergeyFrolov** [SergeyFrolov/gotapdance#1]
![crossplatform_ugliness](https://cloud.githubusercontent.com/assets/5443147/20784804/e2f3e388-b759-11e6-851b-e12caa759715.jpg)
![android_native](https://cloud.githubusercontent.com/assets/5443147/20784805/e2f5fc68-b759-11e6-8517-60890f77a42b.jpg)

**Comment by sergeyfrolov** [comment]
![image](https://user-images.githubusercontent.com/5443147/30133006-7c3019f4-930f-11e7-9f60-3df45ee13d9d.png)
