### ISSUE TITLE
found a segfault

### ISSUE THREAD

**Issue by SalmonProject** [SergeyFrolov/gotapdance#10]
Seems pretty rare; haven't been able to replicate it. This is commit e9db55c52d8e157d8eb90d20dc6641f369ec8bd8, "Log MSG_CLOSE", from yesterday.

[15:32:36] [Flow 115] Successfully connected to Tapdance Station!
[15:32:40] [Flow 60] establishTLStoDecoy() failed with dial tcp 192.122.190.104:443: getsockopt: connection timed out
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x5087d4]

goroutine 446 [running]:
panic(0x74fdc0, 0xc82000a140)
        /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
github.com/zmap/zgrab/ztools/ztls.(*Conn).Handshake(0x0, 0x0, 0x0)
        /home/fred/code/go/src/github.com/zmap/zgrab/ztools/ztls/conn.go:1033 +0x1d4
github.com/zmap/zgrab/ztools/ztls.(*Conn).Read(0x0, 0xc8205e0100, 0x4034, 0x4034, 0x0, 0x0, 0x0)
        /home/fred/code/go/src/github.com/zmap/zgrab/ztools/ztls/conn.go:953 +0x6c
github.com/SergeyFrolov/gotapdance/tapdance.(*tapdanceConn).read_as(0xc8205ae300, 0xc8205e4200, 0x4034, 0x4034, 0x0, 0x0, 0x7f4a24485be8, 0xc8204c1220)
        /home/fred/code/go/src/github.com/SergeyFrolov/gotapdance/tapdance/tdConn.go:214 +0x1af
github.com/SergeyFrolov/gotapdance/tapdance.(*tapdanceConn).Read(0xc8205ae300, 0xc820598100, 0x4034, 0x4034, 0x0, 0x0, 0x0)
        /home/fred/code/go/src/github.com/SergeyFrolov/gotapdance/tapdance/tdConn.go:177 +0xbe
github.com/SergeyFrolov/gotapdance/tapdance.(*TapDanceFlow).Redirect.func1()
        /home/fred/code/go/src/github.com/SergeyFrolov/gotapdance/tapdance/flow.go:58 +0xd8
created by github.com/SergeyFrolov/gotapdance/tapdance.(*TapDanceFlow).Redirect
        /home/fred/code/go/src/github.com/SergeyFrolov/gotapdance/tapdance/flow.go:100 +0x308

**Comment by SergeyFrolov** [comment]
Does not seem to be that commit. Stack trace says that there was an error at 
`/home/fred/code/go/src/github.com/SergeyFrolov/gotapdance/tapdance/tdConn.go:214` but line 214 is a comment:
https://github.com/SergeyFrolov/gotapdance/blob/e9db55c52d8e157d8eb90d20dc6641f369ec8bd8/tapdance/tdConn.go#L214
[15:32:40] [Flow 60] establishTLStoDecoy() error appears unrelated: goroutine that failed establishTLStoDecoy() won't enter Read()
Simplified call trace: td.Read() -> td.read_as() -> ztls.Conn.Read() -> ztls.Conn.Handshake(), and then nil pointer error happened here: https://github.com/zmap/zgrab/blob/f4cc6d29f0b054207a118413f2ff9e99f8dd90df/ztools/ztls/conn.go#L1033
Might be TapDance or ztls' fault.

Let's see if this error shows up again.

**Comment by SalmonProject** [comment]
Got another one, this time when writing:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x5087d4]

goroutine 521 [running]:
panic(0x74fdc0, 0xc82000a140)
        /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
github.com/zmap/zgrab/ztools/ztls.(*Conn).Handshake(0x0, 0x0, 0x0)
        /home/fred/code/go/src/github.com/zmap/zgrab/ztools/ztls/conn.go:1033 +0x1d4
github.com/zmap/zgrab/ztools/ztls.(*Conn).Write(0x0, 0xc820cfe000, 0x1f, 0x8000, 0x0, 0x0, 0x0)
        /home/fred/code/go/src/github.com/zmap/zgrab/ztools/ztls/conn.go:911 +0x4e
github.com/SergeyFrolov/gotapdance/tapdance.(*tapdanceConn).write_as(0xc820148cc0, 0xc820cfe000, 0x1f, 0x8000, 0x0, 0x0, 0x7ffae84bf320, 0xc82108ec80)
        /home/fred/code/go/src/github.com/SergeyFrolov/gotapdance/tapdance/tdConn.go:339 +0x410
github.com/SergeyFrolov/gotapdance/tapdance.(*tapdanceConn).Write(0xc820148cc0, 0xc820cfe000, 0x1f, 0x8000, 0x1f, 0x0, 0x0)
        /home/fred/code/go/src/github.com/SergeyFrolov/gotapdance/tapdance/tdConn.go:321 +0x56
io.copyBuffer(0x7ffae848ac98, 0xc820148cc0, 0x7ffae847d0b0, 0xc8205480f8, 0xc820cfe000, 0x8000, 0x8000, 0x1e8b, 0x0, 0x0)
        /usr/lib/go-1.6/src/io/io.go:382 +0x2c9
io.Copy(0x7ffae848ac98, 0xc820148cc0, 0x7ffae847d0b0, 0xc8205480f8, 0xc8205480f8, 0x0, 0x0)
        /usr/lib/go-1.6/src/io/io.go:350 +0x64
github.com/SergeyFrolov/gotapdance/tapdance.(*TapDanceFlow).Redirect.func2()
        /home/fred/code/go/src/github.com/SergeyFrolov/gotapdance/tapdance/flow.go:87 +0xfc
created by github.com/SergeyFrolov/gotapdance/tapdance.(*TapDanceFlow).Redirect
        /home/fred/code/go/src/github.com/SergeyFrolov/gotapdance/tapdance/flow.go:101 +0x321

Commit 291cc08756924d4bf0f9cb5abc42ca5018c7d4e3 "Major overhaul of Read() logic: cleaner and safer"

**Comment by SergeyFrolov** [comment]
@SalmonProject have you seen any segfaults, since client was significantly redesigned?

**Comment by SalmonProject** [comment]
Nope, not for a long time. Yeah, with all the changes, you might as well close this; either that segfault is now gone, or that stack trace is no longer meaningful to it.

**Comment by SergeyFrolov** [comment]
Ok, thanks.
Please file an issue whenever you see new segfault.
