### ISSUE TITLE
high CPU

### ISSUE THREAD

**Issue by SalmonProject** [SergeyFrolov/gotapdance#11]
After (but not during) successfully loading a web page, the client uses 200-250% CPU on my laptop. Also, eventually, a bunch of these print:

[10:05:23] [Flow 79] Redirect function returns, error: tls: received record with version aa2d when expecting version 303
[10:05:23] [Flow 79] Shut down with error: tls: received record with version aa2d when expecting version 303

When I close the browser that loaded the page, cli goes up to ~350% CPU (probably just because the browser was previously competing).

**Comment by SergeyFrolov** [comment]
I think `tls: received record with version aa2d when expecting version 303` is unrelated to high CPU usage. Wrong tls record is likely a corrupted connection and decryption is done by ztls before TapDance logic. If you still have the log, did it flow79 make Wrte()-induced reconnect just before that happened? There is a nasty bug, that corrupts the connection during that operation.

Will work on high CPU usage.

Thanks for the report!

**Comment by SalmonProject** [comment]
Only a few reconnects happen - one in the middle of everything, and two at the very beginning in flow 1 (which starts upon starting Firefox, before loading any pages).

Looking more closely, it actually looks like *all* flows are ending in that "when expecting version" error.

**Comment by SergeyFrolov** [comment]
High CPU usage is fixed in new channel-based client
