### ISSUE TITLE
Don't always reconnect

### ISSUE THREAD

**Issue by ewust** [SergeyFrolov/gotapdance#13]
If a client hasn't sent (or received) data in a while, we shouldn't keep reconnecting with idle connections. Once we get more data to send, we can restart the decoy connections, but in times of idle, we should generate no traffic.

**Comment by SergeyFrolov** [comment]
@ewust I am not sure if this is high-priority, or even worth doing.
If we are running ssh tunnel over TapDance, then there always will be heartbeat traffic
If we are running `./cli` and connecting from a browser, then those connections will simply get closed

**Comment by SergeyFrolov** [comment]
Another concern: if server wants to send something to client after a few minutes of idle -- it won't be able to do so.
