### ISSUE TITLE
Update list of decoys

### ISSUE THREAD

**Issue by ewust** [SergeyFrolov/gotapdance#14]
Long-term, we need a way to update the list of decoys that a client can use. One idea is to have a new message type from the server that specifies a new config (that specifies new decoy servers, and maybe even public keys) that the client can use.

We might also (for purposes of tracking/debugging) have the client send up its version, and a hash (or ID) of the decoy servers/keys it's using in its tag.

**Comment by SergeyFrolov** [comment]
Implemented in #41
