### ISSUE TITLE
Client exponential backoff

### ISSUE THREAD

**Issue by ewust** [SergeyFrolov/gotapdance#23]
If a connection fails for whatever reason, we shouldn't reconnect immediately. Instead, we should wait an exponentially increasing amount of time based on aggregated failures. @bvandersloot

**Comment by SergeyFrolov** [comment]
Such mechanism already exists.
If you mean the workflow like:

1. client reconnects
2. station sends INIT
3. then station immediately sends FIN/RST (happens sometimes now)
4. client starts reconnect.

then the abovementioned connection should just fail.
And we should just fix the station.

**Comment by bvandersloot** [comment]
What Eric means is that the repeated failed reconnects from the client should have a exponentially increasing delay between attempts.

**Comment by ewust** [comment]
Ah, seems already implemented, and just tested (connecting to non-existing domain).
