### ISSUE TITLE
client panics if server does not choose AES ciphersuite

### ISSUE THREAD

**Issue by Ellard** [SergeyFrolov/gotapdance#3]
As part of the TLS handshake, the client offers a set of ciphersuites to the server, and the server picks the first one that it supports.  Older servers (running older SSL libraries) may choose a ciphersuite that uses RC4.  If this happens, the code for creating the tag causes a panic because it only can handle AES.

If the server chooses a ciphersuite that isn't handled by the tag generator, the client should not panic.  Maybe it should generate some fake traffic, so that it doesn't look strange because it drops the connection immediately after the handshake.

I ran commit 2381dba3ba95a44ede8ab5e9eb3fff7752b4d0c3

The output on the terminal looks like:

```
[11:47:55] Succesfully initialized new Tapdance Proxy. Please press "Launch" to start accepting connections.
[11:47:55] Accepting connections at port 10500
[11:48:21] Flows total: 0. Not picked up: 0. Timed out: 0. Unexpected error: 0. Graceful close: 0
[11:48:21] [Flow 1] Connected to decoy test-host
panic: interface conversion: *rc4.Cipher is not cipher.AEAD: missing method NonceSize

goroutine 5 [running]:
panic(0x68a240, 0xc42006ac80)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/SergeyFrolov/gotapdance/tapdance.(*tapdanceConn).getKeystream(0xc420146300, 0x120, 0xa0, 0xf61b4968b0a7fd3, 0x222966079b07bc38)
	/home/dellard/go/src/github.com/SergeyFrolov/gotapdance/tapdance/tdConn.go:406 +0xd0
github.com/SergeyFrolov/gotapdance/tapdance.(*tapdanceConn).prepareTDRequest(0xc420146300, 0xc42019f770, 0x2d, 0x0, 0x0)
	/home/dellard/go/src/github.com/SergeyFrolov/gotapdance/tapdance/tdConn.go:436 +0x326
github.com/SergeyFrolov/gotapdance/tapdance.(*tapdanceConn).reconnect(0xc420146300, 0x0, 0x0)
	/home/dellard/go/src/github.com/SergeyFrolov/gotapdance/tapdance/tdConn.go:140 +0x3da
github.com/SergeyFrolov/gotapdance/tapdance.DialTapDance(0x1, 0x0, 0xc420146168, 0x461b55, 0xc420146158)
	/home/dellard/go/src/github.com/SergeyFrolov/gotapdance/tapdance/tdConn.go:86 +0x1f6
github.com/SergeyFrolov/gotapdance/tapdance.(*TapDanceFlow).Redirect(0xc4202460f0, 0x0, 0x0)
	/home/dellard/go/src/github.com/SergeyFrolov/gotapdance/tapdance/flow.go:46 +0x9a
github.com/SergeyFrolov/gotapdance/tapdance.(*TapdanceProxy).handleUserConn(0xc4201460c0, 0x959380, 0xc42002a178)
	/home/dellard/go/src/github.com/SergeyFrolov/gotapdance/tapdance/tapdance.go:131 +0xe7
created by github.com/SergeyFrolov/gotapdance/tapdance.(*TapdanceProxy).Listen
	/home/dellard/go/src/github.com/SergeyFrolov/gotapdance/tapdance/tapdance.go:90 +0x240
 ```

**Comment by SergeyFrolov** [comment]
Many thanks for the report!

I added list of supported ciphers: connection now closes gracefully, if client negotiated unsupported one. Later on, when we have multiple decoy websites, we would be able to choose another one. Hopefully, clients on practice would not encounter this error, as the list of decoy websites is in our control and we should not add there any servers, that don't support anything better, than broken RC4. RC4 is not supported by station either, and, I think we'd rather want to focus on extending our support of good ciphers.
I am not sure if bogus random traffic would look less suspicious, than the tear-down after handshake, or if it's worth the effort. We might want to come back to this later, when we focus on fingerprinting-resistant version of TapDance.

**Comment by Ellard** [comment]
It will be noticeable if the list of ciphersuites offered by the client does not exactly match the list of ciphersuites offered by some standard client (chrome, firefox, edge, etc).  I think it would be better to exactly copy one of those lists -- but of course this means that you run the risk of some server choosing one of them, and if that happens then the client must fail gracefully.

**Comment by SergeyFrolov** [comment]
Yes, and that's exactly what' happening. Client still offers old ciphersuites, but would simply and gracefully close connection if RC4 gets negotiated.
Which one of them to copy is a good question: current list is taken from golang ztls implementation.
