### ISSUE TITLE
Client does not always end TLS tunnels with CloseNotify

### ISSUE THREAD

**Issue by SalmonProject** [SergeyFrolov/gotapdance#34]
After careful investigation, I am completely sure that many client TLS tunnels (say around half, very approximately) have their TCP streams close without the client having sent a TLS CloseNotify. It's definitely the client closing them; the Rust part of the station never even sees the socket fd, and I have confirmed that the station does not SSL_shutdown() or SSL_free() the owning SSL objects beforehand. Sometimes the station encounters the closed socket via attempting an SSL_read(), and sometimes via attempting an SSL_write(), so there doesn't appear to be anything in particular the station is doing to trigger it.

This issue is currently mitigated by the station treating SSL-underlying syscall errors as clean TLS shutdowns, but that's not really correct logic.

**Comment by SergeyFrolov** [comment]
It is not TapDance issue, not much we can do. Also, it's mitigated by protobufs.
