### ISSUE TITLE
Offer ciphersuite list, identical to mobile Chrome/Firefox/something else

### ISSUE THREAD

**Issue by sergeyfrolov** [sergeyfrolov/gotapdance#4]
As discussed in #3, we'd want our client hello to look like one of popular browsers.
Current list of ciphersuites is dictated by ztls, which is likely to be detectable.

**Comment by SergeyFrolov** [comment]
Some work on this is done in ztls:
https://github.com/zmap/zgrab/pull/214
https://github.com/zmap/zgrab/pull/220
