### ISSUE TITLE
Client leaves sessions hanging

### ISSUE THREAD

**Issue by SalmonProject** [SergeyFrolov/gotapdance#44]
The client will fairly often abandon a session: it says to expect a reconnect, cleanly shuts down the current stream, and then never comes back. This can (and will) be handled by a timeout on the station, but the bug in the client is still worth investigating for the sake of clean code, and in case there are any side effects we haven't realized yet.

**Comment by SergeyFrolov** [comment]
Please include logs.

**Comment by SalmonProject** [comment]
(you have figured this one out I think)

**Comment by SalmonProject** [comment]
Still appears to be a problem. In load testing, ~29k out of ~33k sessions ended with the client ending a stream with "EXPECT_RECONNECT", and then never coming back, so that the 30 second session time-out had to end the session.

**Comment by SergeyFrolov** [comment]
Thanks for that report.
However, I still need logs, preferably from client, station and wire, but I'll take whatever logs you have.
Reproducer also sounds great.
In any case, I will need at least anything to start.

Also, according to person, running the test:
> no, things looked good on my end

Which is also not representative, of course, nevertheless things _might_ be good on that end. Without logs I might just as well submit the exactly same issue to server with exactly same description

**Comment by SergeyFrolov** [comment]
Just to be explicit: I recognize that there is an issue. 
This could be the same issue as "FIN await timeout", in which we did confirm that client didn't receive FIN back on the wire *at least once* when I first tried it while pcap'ing on the router.

**Comment by SalmonProject** [comment]
Right, things would definitely look fine on the client end, or else the client would have tried to take some other action. Nothing that the client prints in its normal operation is going to be meaningful here. You should debug-log the client up, and do a bunch of wgets. There is nothing else useful I can provide you with right now.

**Comment by SergeyFrolov** [comment]
_Things would definitely look fine on the server end, or else the server would have tried to take some other action. Nothing that the server prints in its normal operation is going to be meaningful here. You should debug-log the everything up, and do a bunch of wgets._

**Comment by SergeyFrolov** [comment]
> You should debug-log the client up, and do a bunch of wgets

I did even more comprehensive debug-logging and client didn't receive the FIN back.
There is nothing client can do about it.

**Comment by SergeyFrolov** [comment]
Not an issue: we'd expect majority of sessions end in error. Users just enable Client App and leave it running for hours/days while they move around: such connection is just destined to die, unless user manually disables Client App. In other words, if user didn't disable Client App -- station naturally is not getting the SESSION_CLOSE
