### ISSUE TITLE
High CPU usage (Linux command line cli)

### ISSUE THREAD

**Issue by SalmonProject** [SergeyFrolov/gotapdance#5]
With cli running, I take a Firefox configured to use SSL proxy 127.0.0.1:10500, visit bing.com, and do a search. After a couple of seconds, CPU usage on my laptop rises to ~250-300%. It stays there permanently (or at least on the order of minutes), even after completely quitting the Firefox instance.

Firefox sends out a few connections right when it starts up, and these do not cause any significant CPU use. Neither does just loading bing.com.

**Comment by SalmonProject** [comment]
Looks like I was using an old version of the client.

**Comment by SergeyFrolov** [comment]
Thanks for report.
Yes this issue was fixed in commit 9119ea3220562ccc5359e97c49cf1a91d6dc4911.
I'd recommend rebuilding your client using
`go build -a .`
