### ISSUE TITLE
Going Apache

### ISSUE THREAD

**Issue by sergeyfrolov** [sergeyfrolov/gotapdance#52]
Currently, gotapdance source code is GPL licensed.

However, in order to provide free access to Internet for everyone, we found a need to move to Apache 2, and allow non-GPL-compatible apps to use TapDance.

There are many contributors in this whole project, but only the following have any code remaining in client:
- [x] @SergeyFrolov
- [x] @bvandersloot 
- [x] @IUdalov 
- [x] @SalmonProject 
- [ ] @christinelaine 

Please confirm in this issue that you agree with releasing the code, that you contributed to gotapdance, under Apache 2 license going forward. You can find Apache 2 license here: https://www.apache.org/licenses/LICENSE-2.0.html

Thank you for your past contributions, and I hope to work more with you in future!

**Comment by sergeyfrolov** [comment]
I agree with releasing my code contributions to this project under Apache 2 License!

**Comment by bvandersloot** [comment]
I, too, agree with releasing my code contributions to this project under Apache 2 License!

**Comment by IUdalov** [comment]
I agree with releasing my code contributions to this project under Apache 2 License!

**Comment by SalmonProject** [comment]
I (SalmonProject) am fine with that.

**Comment by SalmonProject** [comment]
I agree with releasing my code contributions to this project under Apache 2 License!

**Comment by sergeyfrolov** [comment]
Looks like account of @christinelaine is unmaintained. I wish her luck in her future endeavors, and, for now, I will simply revert her commit in #0c1451be3a719603da7fde553fcaeb49d6528fc6
Which means that everyone, who has any code remaining in gotapdance, has agreed to move to Apache 2! :tada:

Many thanks to all contributors!
