### ISSUE TITLE
provide a way to specify location of ClientConf file

### ISSUE THREAD

**Issue by dellard** [sergeyfrolov/gotapdance#55]
The cli takes its parameters (decoys, keys, etc) from the ClientConf file, which currently needs to have a specific name and be located in a specific path relative to the cli executable (or maybe it needs to be in ./assets/ClientConf relative to where the cwd?)

For some of the experiments we run, such as the decoy prober, we make lots of these configuration files and we need to keep copying them into the right directory (or, when we're running multiple cli processes concurrently, we need to make a bunch of scratch directories and copy them there).  It would make things much simpler if we could pass the path to the configuration file on the commandline to cli.  I would suggest something like `-f` as the name for this option.

**Comment by sergeyfrolov** [comment]
Added a way to specify location of assets folder.
@dellard does this API fit your use-case?
