### ISSUE TITLE
Cannot find proxybind

### ISSUE THREAD

**Issue by MercuryOoO** [sergeyfrolov/gotapdance#57]
Gradlew complaint: cannot find package github.com/sergeyfrolov/gotapdance/proxybind
In fact there isn't github.com/sergeyfrolov/gotapdance/proxybind at all.

**Comment by sergeyfrolov** [comment]
Please take a look at https://github.com/sergeyfrolov/gotapdance/tree/master/gobind#note
With that being said, the problem is fixed.
Thanks for report!
